Repository inDevelopme/justaskdavidb-vuestic-ui, pull requests merged in 2025-07, with the labels that each got.

#22 #21 Test Workflow Branch Demonstration
  src/views/WorkflowView.vue
Labels: documentation

#23 Create WorkflowView.vue (#22)
  src/views/WorkflowView.vue
Labels: documentation, enhancement

#24 19 feature add test logic to ci workflow
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/components/HelloWorld.vue
  src/components/__tests__/HelloWorld.spec.js
  src/views/WorkflowView.vue
  tests/example.test.ts
Labels: enhancement
